jwt:
  expiration: 604800 #JWT过期时间(60 * 60 * 24 * 7)
  header: Authorization
  secret: linlu-wms
  duration: 1200000 # 有效期不足20分钟时续期(20 * 60 * 1000)
spring:
  application:
    name: wms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root@mysql
  auth:
    ignored:
      urls:
        - /swagger-ui/
        - /**/v2/api-docs
        - /login
        - /register
